name: Helm Publish

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:
  helm:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        run: |
          helm dep up .

      - name: Build the Helm Chart
        run: |
          helm package . -u --destination ./dist

      - name: Publish Helm Chart
        run: |
          echo "${{ secrets.GITHUB_TOKEN}}" | helm registry login ghcr.io/${{github.repository}} --username ${GITHUB_ACTOR} --password-stdin
          helm push ./dist/redis-*.tgz oci://ghcr.io/${{github.repository}}
